<?php

namespace Kanekescom\Siasn\Api\Simpeg\Transformers;

use League\Fractal\TransformerAbstract;

class DataUtamaTransformer extends TransformerAbstract
{
    /**
     * Transform the DataUtama model.
     *
     * @param  Kanekescom\Siasn\Simpeg\Models\DataUtama  $model
     */
    public function transform(array $item): array
    {
        return [
            'id' => $item['id'],
            'nip_baru' => $item['nipBaru'],
            'nip_lama' => $item['nipLama'],
            'nama' => $item['nama'],
            'gelar_depan' => $item['gelarDepan'],
            'gelar_belakang' => $item['gelarBelakang'],
            'tempat_lahir' => $item['tempatLahir'],
            'tempat_lahir_id' => $item['tempatLahirId'],
            'tgl_lahir' => $item['tglLahir'],
            'agama' => $item['agama'],
            'agama_id' => $item['agamaId'],
            'email' => $item['email'],
            'email_gov' => $item['emailGov'],
            'nik' => $item['nik'],
            'alamat' => $item['alamat'],
            'no_hp' => $item['noHp'],
            'no_telp' => $item['noTelp'],
            'jenis_pegawai_id' => $item['jenisPegawaiId'],
            'mk_tahun' => $item['mkTahun'],
            'mk_bulan' => $item['mkBulan'],
            'jenis_pegawai_nama' => $item['jenisPegawaiNama'],
            'kedudukan_pns_id' => $item['kedudukanPnsId'],
            'kedudukan_pns_nama' => $item['kedudukanPnsNama'],
            'status_pegawai' => $item['statusPegawai'],
            'jenis_kelamin' => $item['jenisKelamin'],
            'jenis_id_dokumen_id' => $item['jenisIdDokumenId'],
            'jenis_id_dokumen_nama' => $item['jenisIdDokumenNama'],
            'nomor_id_document' => $item['nomorIdDocument'],
            'no_seri_karpeg' => $item['noSeriKarpeg'],
            'tk_pendidikan_terakhir_id' => $item['tkPendidikanTerakhirId'],
            'tk_pendidikan_terakhir' => $item['tkPendidikanTerakhir'],
            'pendidikan_terakhir_id' => $item['pendidikanTerakhirId'],
            'pendidikan_terakhir_nama' => $item['pendidikanTerakhirNama'],
            'tahun_lulus' => $item['tahunLulus'],
            'tmt_pns' => $item['tmtPns'],
            'tmt_pensiun' => $item['tmtPensiun'],
            'bup_pensiun' => $item['bupPensiun'],
            'tgl_sk_pns' => $item['tglSkPns'],
            'tmt_cpns' => $item['tmtCpns'],
            'tgl_sk_cpns' => $item['tglSkCpns'],
            'instansi_induk_id' => $item['instansiIndukId'],
            'instansi_induk_nama' => $item['instansiIndukNama'],
            'satuan_kerja_induk_id' => $item['satuanKerjaIndukId'],
            'satuan_kerja_induk_nama' => $item['satuanKerjaIndukNama'],
            'kanreg_id' => $item['kanregId'],
            'kanreg_nama' => $item['kanregNama'],
            'instansi_kerja_id' => $item['instansiKerjaId'],
            'instansi_kerja_nama' => $item['instansiKerjaNama'],
            'instansi_kerja_kode_cepat' => $item['instansiKerjaKodeCepat'],
            'satuan_kerja_kerja_id' => $item['satuanKerjaKerjaId'],
            'satuan_kerja_kerja_nama' => $item['satuanKerjaKerjaNama'],
            'unor_id' => $item['unorId'],
            'unor_nama' => $item['unorNama'],
            'unor_induk_id' => $item['unorIndukId'],
            'unor_induk_nama' => $item['unorIndukNama'],
            'jenis_jabatan_id' => $item['jenisJabatanId'],
            'jenis_jabatan' => $item['jenisJabatan'],
            'jabatan_nama' => $item['jabatanNama'],
            'jabatan_struktural_id' => $item['jabatanStrukturalId'],
            'jabatan_struktural_nama' => $item['jabatanStrukturalNama'],
            'jabatan_fungsional_id' => $item['jabatanFungsionalId'],
            'jabatan_fungsional_nama' => $item['jabatanFungsionalNama'],
            'jabatan_fungsional_umum_id' => $item['jabatanFungsionalUmumId'],
            'jabatan_fungsional_umum_nama' => $item['jabatanFungsionalUmumNama'],
            'tmt_jabatan' => $item['tmtJabatan'],
            'lokasi_kerja_id' => $item['lokasiKerjaId'],
            'lokasi_kerja' => $item['lokasiKerja'],
            'gol_ruang_awal_id' => $item['golRuangAwalId'],
            'gol_ruang_awal' => $item['golRuangAwal'],
            'gol_ruang_akhir_id' => $item['golRuangAkhirId'],
            'gol_ruang_akhir' => $item['golRuangAkhir'],
            'tmt_gol_akhir' => $item['tmtGolAkhir'],
            'masa_kerja' => $item['masaKerja'],
            'eselon' => $item['eselon'],
            'eselon_id' => $item['eselonId'],
            'eselon_level' => $item['eselonLevel'],
            'tmt_eselon' => $item['tmtEselon'],
            'gaji_pokok' => $item['gajiPokok'],
            'kpkn_id' => $item['kpknId'],
            'kpkn_nama' => $item['kpknNama'],
            'ktua_id' => $item['ktuaId'],
            'ktua_nama' => $item['ktuaNama'],
            'taspen_id' => $item['taspenId'],
            'taspen_nama' => $item['taspenNama'],
            'jenis_kawin_id' => $item['jenisKawinId'],
            'status_perkawinan' => $item['statusPerkawinan'],
            'status_hidup' => $item['statusHidup'],
            'tgl_surat_keterangan_dokter' => $item['tglSuratKeteranganDokter'],
            'no_surat_keterangan_dokter' => $item['noSuratKeteranganDokter'],
            'jumlah_istri_suami' => $item['jumlahIstriSuami'],
            'jumlah_anak' => $item['jumlahAnak'],
            'no_surat_keterangan_bebas_narkoba' => $item['noSuratKeteranganBebasNarkoba'],
            'tgl_surat_keterangan_bebas_narkoba' => $item['tglSuratKeteranganBebasNarkoba'],
            'skck' => $item['skck'],
            'tgl_skck' => $item['tglSkck'],
            'akte_kelahiran' => $item['akteKelahiran'],
            'akte_meninggal' => $item['akteMeninggal'],
            'tgl_meninggal' => $item['tglMeninggal'],
            'no_npwp' => $item['noNpwp'],
            'tgl_npwp' => $item['tglNpwp'],
            'no_askes' => $item['noAskes'],
            'bpjs' => $item['bpjs'],
            'kode_pos' => $item['kodePos'],
            'no_spmt' => $item['noSpmt'],
            'no_taspen' => $item['noTaspen'],
            'bahasa' => $item['bahasa'],
            'kppn_id' => $item['kppnId'],
            'kppn_nama' => $item['kppnNama'],
            'pangkat_akhir' => $item['pangkatAkhir'],
            'tgl_sttpl' => $item['tglSttpl'],
            'nomor_sttpl' => $item['nomorSttpl'],
            'nomor_sk_cpns' => $item['nomorSkCpns'],
            'nomor_sk_pns' => $item['nomorSkPns'],
            'jenjang' => $item['jenjang'],
            'jabatan_asn' => $item['jabatanAsn'],
            'kartu_asn' => $item['kartuAsn'],
        ];
    }
}
